# -*- coding: utf-8 -*-
"""가로등 전처리2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oADmAktVd3okQDWXqeyZ0JN6xC347j93
"""

# ① 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# ② 파일 경로 설정 및 로드
import glob

# ↓ 본인 드라이브 폴더 경로로 수정
DRIVE_PATH = '/content/drive/MyDrive/가로등/'

# 폴더 안 CSV 파일 전체 탐색
csv_files = glob.glob(DRIVE_PATH + '*.csv')
print(f'발견된 파일 수: {len(csv_files)}개')
for f in csv_files:
    print(' -', f)

import pandas as pd
import os
import chardet

# 함수 정의 (NameError 해결을 위해 이동)
def detect_encoding(filepath):
    """파일 인코딩 자동 감지"""
    with open(filepath, 'rb') as f:
        raw = f.read(50000)  # 처음 50KB만 샘플링
    result = chardet.detect(raw)
    return result['encoding']


def load_csv_safe(filepath):
    """인코딩 자동 감지 후 안전하게 CSV 로드"""
    encodings_to_try = ['utf-8', 'cp949', 'euc-kr', 'utf-8-sig']

    # chardet 으로 먼저 시도
    detected = detect_encoding(filepath)
    if detected:
        encodings_to_try.insert(0, detected)

    for enc in encodings_to_try:
        try:
            df = pd.read_csv(filepath, encoding=enc, low_memory=False)
            print(f'  ✅ [{os.path.basename(filepath)}] 인코딩: {enc}  |  행: {len(df):,}')
            return df
        except Exception:
            continue

    raise ValueError(f'❌ {filepath} 파일 읽기 실패 - 인코딩을 확인하세요.')

dfs = []
for fpath in csv_files:
    df_tmp = load_csv_safe(fpath)
    df_tmp['_원본파일명'] = os.path.basename(fpath)
    dfs.append(df_tmp)

df_raw = pd.concat(dfs, ignore_index=True)
print(f'\n📊 병합 결과: {df_raw.shape[0]:,}행 × {df_raw.shape[1]}열')

"""## 3. CSV 인코딩 감지 및 로딩 함수"""

def detect_encoding(filepath):
    """파일 인코딩 자동 감지"""
    with open(filepath, 'rb') as f:
        raw = f.read(50000)  # 처음 50KB만 샘플링
    result = chardet.detect(raw)
    return result['encoding']


def load_csv_safe(filepath):
    """인코딩 자동 감지 후 안전하게 CSV 로드"""
    encodings_to_try = ['utf-8', 'cp949', 'euc-kr', 'utf-8-sig']

    # chardet 으로 먼저 시도
    detected = detect_encoding(filepath)
    if detected:
        encodings_to_try.insert(0, detected)

    for enc in encodings_to_try:
        try:
            df = pd.read_csv(filepath, encoding=enc, low_memory=False)
            print(f'  ✅ [{os.path.basename(filepath)}] 인코딩: {enc}  |  행: {len(df):,}')
            return df
        except Exception:
            continue

    raise ValueError(f'❌ {filepath} 파일 읽기 실패 - 인코딩을 확인하세요.')


print('✅ 함수 정의 완료')

"""## 4. 전체 파일 로드 및 병합"""

# ── 업로드된 파일 모두 읽어서 병합 ──
dfs = []
for fname in csv_files:
    df_tmp = load_csv_safe(fname)
    df_tmp['_원본파일명'] = fname  # 출처 파일 추적용
    dfs.append(df_tmp)

df_raw = pd.concat(dfs, ignore_index=True)

print(f'\n📊 전체 병합 결과: {df_raw.shape[0]:,}행 × {df_raw.shape[1]}열')
display(df_raw.head(3))

"""## 5. 컬럼명 표준화 및 확인"""

# 실제 컬럼 확인
print('📋 원본 컬럼명:')
for i, col in enumerate(df_raw.columns):
    print(f'  [{i}] {col}')

# ── 표준 컬럼명 매핑 (공공데이터포털 표준 기준) ──
# 실제 파일의 컬럼명과 다를 경우 아래 딕셔너리를 수정하세요.
COLUMN_MAP = {
    '보안등위치명':       '보안등위치명',
    '설치개수':           '설치개수',
    '소재지도로명주소':   '소재지도로명주소',
    '소재지지번주소':     '소재지지번주소',
    '위도':               '위도',
    '경도':               '경도',
    '설치연도':           '설치연도',
    '설치형태':           '설치형태',
    '관리기관전화번호':   '관리기관전화번호',
    '관리기관명':         '관리기관명',
    '데이터기준일자':     '데이터기준일자',
}

# 존재하는 컬럼만 이름 변경
existing_map = {k: v for k, v in COLUMN_MAP.items() if k in df_raw.columns}
df_raw = df_raw.rename(columns=existing_map)

print('✅ 컬럼명 표준화 완료')
print(df_raw.dtypes)

"""## 6. 서울시 25개 자치구 필터링"""

SEOUL_25_GU = [
    '강남구', '강동구', '강북구', '강서구', '관악구',
    '광진구', '구로구', '금천구', '노원구', '도봉구',
    '동대문구', '동작구', '마포구', '서대문구', '서초구',
    '성동구', '성북구', '송파구', '양천구', '영등포구',
    '용산구', '은평구', '종로구', '중구', '중랑구'
]

# 주소 컬럼에서 서울 자치구 포함 여부로 필터
addr_col = '소재지도로명주소'  # 또는 '소재지지번주소'

# 서울시 + 자치구 패턴으로 필터링
seoul_pattern = '|'.join([f'서울.*{gu}' for gu in SEOUL_25_GU])
mask_seoul = df_raw[addr_col].str.contains('서울', na=False)

df_seoul = df_raw[mask_seoul].copy()

print(f'✅ 서울시 데이터 필터링 완료: {len(df_seoul):,}건')
print(f'   전체 대비 비율: {len(df_seoul)/len(df_raw)*100:.1f}%')

# ── 자치구 컬럼 추출 ──
def extract_gu(address):
    """주소 문자열에서 자치구명 추출"""
    if pd.isna(address):
        return None
    for gu in SEOUL_25_GU:
        if gu in str(address):
            return gu
    return None

df_seoul['자치구'] = df_seoul[addr_col].apply(extract_gu)

print('📊 자치구별 데이터 건수:')
gu_count = df_seoul['자치구'].value_counts().sort_index()
display(gu_count.to_frame('건수'))

print(f'\n자치구 인식 실패: {df_seoul["자치구"].isna().sum()}건')

"""## 7. 데이터 타입 변환 및 결측치 처리"""

# ── 결측치 현황 ──
print('🔍 결측치 현황:')
missing = df_seoul.isnull().sum()
missing_pct = (missing / len(df_seoul) * 100).round(2)
missing_df = pd.DataFrame({'결측수': missing, '결측률(%)': missing_pct})
display(missing_df[missing_df['결측수'] > 0])

# ── 위도/경도 숫자형 변환 ──
df_seoul['위도'] = pd.to_numeric(df_seoul['위도'], errors='coerce')
df_seoul['경도'] = pd.to_numeric(df_seoul['경도'], errors='coerce')
df_seoul['설치개수'] = pd.to_numeric(df_seoul['설치개수'], errors='coerce')
df_seoul['설치연도'] = pd.to_numeric(df_seoul['설치연도'], errors='coerce')

print('✅ 데이터 타입 변환 완료')
print(df_seoul[['위도', '경도', '설치개수', '설치연도']].dtypes)

"""## 8. 좌표 유효성 검증 (서울 범위 필터)"""

# 서울시 위경도 범위 (WGS84 기준)
SEOUL_LAT_MIN, SEOUL_LAT_MAX = 37.413, 37.716
SEOUL_LON_MIN, SEOUL_LON_MAX = 126.734, 127.269

# 유효 좌표 마스크
valid_coord_mask = (
    df_seoul['위도'].between(SEOUL_LAT_MIN, SEOUL_LAT_MAX) &
    df_seoul['경도'].between(SEOUL_LON_MIN, SEOUL_LON_MAX)
)

n_invalid = (~valid_coord_mask).sum()
print(f'🚨 유효하지 않은 좌표: {n_invalid}건')

if n_invalid > 0:
    print('\n문제 있는 데이터 샘플:')
    display(df_seoul[~valid_coord_mask][['보안등위치명', '위도', '경도', '소재지도로명주소']].head(10))

# 유효 좌표만 유지 (비율 확인 후 결정)
df_valid = df_seoul[valid_coord_mask].copy()
print(f'\n✅ 유효 좌표 데이터: {len(df_valid):,}건 / 전체 {len(df_seoul):,}건')

"""## 9. 이상치 탐지 및 중복 제거"""

# ── 완전 중복 행 제거 ──
n_before = len(df_valid)
df_valid = df_valid.drop_duplicates()
print(f'🗑 중복 행 제거: {n_before - len(df_valid)}건 제거 → {len(df_valid):,}건 남음')

# ── 동일 좌표 중복 탐지 ──
coord_dupes = df_valid.duplicated(subset=['위도', '경도'], keep=False)
print(f'\n⚠️  동일 좌표 중복: {coord_dupes.sum()}건')
if coord_dupes.sum() > 0:
    print('  → 동일 위치에 여러 보안등 레코드가 있는 경우입니다.')
    print('  → 필요시 아래 셀에서 대표값 집계를 사용하세요.')

# ── 설치개수 이상치 확인 ──
print('📊 설치개수 기술통계:')
display(df_valid['설치개수'].describe())

# IQR 기반 이상치 탐지
Q1 = df_valid['설치개수'].quantile(0.25)
Q3 = df_valid['설치개수'].quantile(0.75)
IQR = Q3 - Q1
outlier_mask = df_valid['설치개수'] > (Q3 + 3 * IQR)
print(f'\n🚨 설치개수 극단 이상치 (Q3+3*IQR 초과): {outlier_mask.sum()}건')
if outlier_mask.sum() > 0:
    display(df_valid[outlier_mask][['자치구', '보안등위치명', '설치개수']].sort_values('설치개수', ascending=False))

"""## 10. 전처리 결과 시각화"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('서울시 보안등 데이터 전처리 결과 요약', fontsize=15, fontweight='bold', y=1.02)

# ① 자치구별 보안등 건수
gu_cnt = df_valid.groupby('자치구')['설치개수'].sum().sort_values(ascending=True)
gu_cnt.plot(kind='barh', ax=axes[0], color='steelblue')
axes[0].set_title('자치구별 보안등 설치 총 개수')
axes[0].set_xlabel('설치 개수')

# ② 설치연도 분포
yr = df_valid['설치연도'].dropna()
yr = yr[(yr >= 1990) & (yr <= 2030)]
axes[1].hist(yr, bins=30, color='coral', edgecolor='white')
axes[1].set_title('설치연도 분포')
axes[1].set_xlabel('연도')
axes[1].set_ylabel('건수')

# ③ 설치형태 파이차트
if '설치형태' in df_valid.columns:
    form_cnt = df_valid['설치형태'].value_counts()
    axes[2].pie(form_cnt.values, labels=form_cnt.index,
                autopct='%1.1f%%', startangle=140,
                colors=plt.cm.Pastel1.colors)
    axes[2].set_title('설치형태 비율')
else:
    axes[2].text(0.5, 0.5, '설치형태 컬럼 없음', ha='center', va='center')

plt.tight_layout()
plt.savefig('보안등_전처리_요약.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ 차트 저장: 보안등_전처리_요약.png')

"""## 11. Folium 지도 시각화 (샘플 500건)"""

# 서울 중심 좌표
SEOUL_CENTER = [37.5665, 126.9780]

m = folium.Map(location=SEOUL_CENTER, zoom_start=11, tiles='CartoDB positron')

# 샘플 500건만 시각화 (전체는 너무 느림)
sample = df_valid.dropna(subset=['위도', '경도']).sample(min(500, len(df_valid)), random_state=42)

for _, row in sample.iterrows():
    popup_text = f"""
    <b>{row.get('보안등위치명', '이름없음')}</b><br>
    자치구: {row.get('자치구', '-')}<br>
    설치개수: {row.get('설치개수', '-')}<br>
    설치연도: {row.get('설치연도', '-')}<br>
    설치형태: {row.get('설치형태', '-')}
    """
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=3,
        color='#FF6B35',
        fill=True,
        fill_opacity=0.7,
        popup=folium.Popup(popup_text, max_width=200)
    ).add_to(m)

m.save('서울시_보안등_지도.html')
print(f'✅ 지도 저장 완료: 서울시_보안등_지도.html ({len(sample)}개 마커)')
m

"""## 12. 최종 데이터 저장"""

# ── 최종 컬럼 선택 ──
FINAL_COLS = [
    '자치구', '보안등위치명', '설치개수',
    '소재지도로명주소', '소재지지번주소',
    '위도', '경도',
    '설치연도', '설치형태',
    '관리기관명', '관리기관전화번호', '데이터기준일자'
]

# 실제 존재하는 컬럼만 선택
final_cols_exist = [c for c in FINAL_COLS if c in df_valid.columns]
df_final = df_valid[final_cols_exist].copy()

# 자치구 기준 정렬
df_final = df_final.sort_values(['자치구', '보안등위치명']).reset_index(drop=True)

print(f'📦 최종 데이터: {df_final.shape[0]:,}행 × {df_final.shape[1]}열')
display(df_final.head())

# ── CSV 저장 (UTF-8 BOM, 엑셀 호환) ──
OUTPUT_CSV = '서울시_보안등_전처리완료.csv'
df_final.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
print(f'✅ CSV 저장 완료: {OUTPUT_CSV}')

# ── 자치구별 통계 저장 ──
gu_stats = df_final.groupby('자치구').agg(
    레코드수=('보안등위치명', 'count'),
    총설치개수=('설치개수', 'sum'),
    평균설치개수=('설치개수', 'mean'),
    최소연도=('설치연도', 'min'),
    최대연도=('설치연도', 'max'),
).round(2).reset_index()

OUTPUT_STATS = '서울시_보안등_자치구별통계.csv'
gu_stats.to_csv(OUTPUT_STATS, index=False, encoding='utf-8-sig')
print(f'✅ 통계 저장 완료: {OUTPUT_STATS}')
display(gu_stats)

# ── Colab에서 파일 다운로드 ──
from google.colab import files

files.download(OUTPUT_CSV)
files.download(OUTPUT_STATS)
files.download('서울시_보안등_지도.html')
files.download('보안등_전처리_요약.png')
print('📥 파일 다운로드 시작됨')