# -*- coding: utf-8 -*-
"""서울시_가로등_전처리.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDR59fglpH4GrikTs0u9oGzGimT9Y4Jy

# 🔦 서울시 가로등 위치 데이터 전처리

**데이터 개요**
- 총 19,316건의 가로등 위치 정보
- 컬럼: `관리번호`, `위도`, `경도`
- 인코딩: CP949 (EUC-KR)
- 발견된 이슈: 용비교 구간 25건 좌표 오류 (위도=0, 경도=4664046)

## Step 1. 라이브러리 설치 및 데이터 로드
"""

# 필요 라이브러리 설치 (Colab에서 folium은 별도 설치)
!pip install folium -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import folium
from google.colab import files

# 한글 폰트 설정 (Colab)
!apt-get install -y fonts-nanum -q
# matplotlib.font_manager._rebuild() # Deprecated in newer matplotlib versions
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['axes.unicode_minus'] = False

print('✅ 라이브러리 로드 완료')

# ─────────────────────────────────────────────
# 파일 업로드 (Colab에서 직접 업로드)
# ─────────────────────────────────────────────
uploaded = files.upload()  # 파일 선택 창이 뜨면 CSV를 선택하세요

filename = list(uploaded.keys())[0]
print(f'업로드된 파일: {filename}')

# CP949 인코딩으로 읽기
df_raw = pd.read_csv(filename, encoding='cp949')

print(f'📊 원본 데이터 shape: {df_raw.shape}')
print()
print(df_raw.head(10))
print()
print('▶ 컬럼 타입:')
print(df_raw.dtypes)

"""## Step 2. 데이터 품질 점검"""

print('=' * 50)
print('📋 기본 통계')
print('=' * 50)
print(df_raw.describe())

print()
print('=' * 50)
print('🔍 결측치 현황')
print('=' * 50)
missing = df_raw.isnull().sum()
print(missing)
print(f'→ 결측치 있는 컬럼: {(missing > 0).sum()}개')

print()
print('=' * 50)
print('🔁 중복 행')
print('=' * 50)
dup = df_raw.duplicated().sum()
print(f'→ 중복 행: {dup}건')

print()
print('=' * 50)
print('🌏 좌표 범위')
print('=' * 50)
print(f'위도 범위: {df_raw["위도"].min():.6f} ~ {df_raw["위도"].max():.6f}  (서울 정상범위: 37.4 ~ 37.7)')
print(f'경도 범위: {df_raw["경도"].min():.6f} ~ {df_raw["경도"].max():.6f}  (서울 정상범위: 126.7 ~ 127.2)')

# ─────────────────────────────────────────────
# 좌표 이상치 탐지
# ─────────────────────────────────────────────
SEOUL_LAT_MIN, SEOUL_LAT_MAX = 37.4, 37.7
SEOUL_LON_MIN, SEOUL_LON_MAX = 126.7, 127.2

mask_outlier = (
    (df_raw['위도'] < SEOUL_LAT_MIN) | (df_raw['위도'] > SEOUL_LAT_MAX) |
    (df_raw['경도'] < SEOUL_LON_MIN) | (df_raw['경도'] > SEOUL_LON_MAX)
)

df_outliers = df_raw[mask_outlier].copy()

print(f'⚠️  좌표 이상치: {len(df_outliers)}건')
print()
print(df_outliers)

# 이상치 관리번호 패턴 확인
print('이상치 관리번호 목록:')
print(df_outliers['관리번호'].unique())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].hist(df_raw['위도'], bins=100, color='steelblue', edgecolor='white')
axes[0].axvline(SEOUL_LAT_MIN, color='red', linestyle='--', label='서울 경계')
axes[0].axvline(SEOUL_LAT_MAX, color='red', linestyle='--')
axes[0].set_title('위도 분포')
axes[0].set_xlabel('위도')
axes[0].legend()

axes[1].hist(df_raw[df_raw['경도'] < 200]['경도'], bins=100, color='coral', edgecolor='white')
axes[1].axvline(SEOUL_LON_MIN, color='red', linestyle='--', label='서울 경계')
axes[1].axvline(SEOUL_LON_MAX, color='red', linestyle='--')
axes[1].set_title('경도 분포 (이상치 제외)')
axes[1].set_xlabel('경도')
axes[1].legend()

plt.tight_layout()
plt.show()

"""## Step 3. 전처리"""

df = df_raw.copy()

# ── 3-1. 중복 제거 ──────────────────────────
before = len(df)
df = df.drop_duplicates()
print(f'[중복 제거] {before} → {len(df)}행 ({before - len(df)}건 제거)')

# ── 3-2. 결측치 제거 ────────────────────────
before = len(df)
df = df.dropna(subset=['위도', '경도', '관리번호'])
print(f'[결측치 제거] {before} → {len(df)}행 ({before - len(df)}건 제거)')

# ── 3-3. 좌표 이상치 처리 ───────────────────
# 이상치는 별도 저장 후 정상 데이터만 유지
mask_valid = (
    df['위도'].between(SEOUL_LAT_MIN, SEOUL_LAT_MAX) &
    df['경도'].between(SEOUL_LON_MIN, SEOUL_LON_MAX)
)
before = len(df)
df_invalid = df[~mask_valid].copy()   # 이상치 별도 보관
df = df[mask_valid].copy()            # 정상 데이터만
print(f'[좌표 이상치 제거] {before} → {len(df)}행 ({before - len(df)}건 제거)')

# ── 3-4. 관리번호에서 구역명/번호 분리 ──────
# 형식: '가락지하차도-01' → 구역명='가락지하차도', 순번='01'
split = df['관리번호'].str.rsplit('-', n=1, expand=True)
df['구역명'] = split[0].str.strip()
df['순번'] = split[1].str.strip().str.zfill(3)  # 3자리 0패딩

# ── 3-5. 컬럼 순서 정리 ─────────────────────
df = df[['관리번호', '구역명', '순번', '위도', '경도']].reset_index(drop=True)

print()
print('✅ 전처리 완료!')
print(f'최종 행 수: {len(df):,}건')
print()
print(df.head(10))

# 전처리 결과 요약
print('=' * 45)
print('📊 전처리 전후 비교')
print('=' * 45)
print(f'  원본 데이터 : {len(df_raw):>6,}건')
print(f'  이상치 제거 : {len(df_invalid):>6,}건')
print(f'  최종 데이터 : {len(df):>6,}건')
print()
print(f'  구역명 종류 : {df["구역명"].nunique():,}개')
print()
print('▶ 최종 데이터 컬럼 타입:')
print(df.dtypes)
print()
print('▶ 최종 데이터 기술통계:')
print(df[['위도','경도']].describe().round(6))

"""## Step 4. 탐색적 데이터 분석 (EDA)"""

# 구역별 가로등 수 Top 20
top_zones = df['구역명'].value_counts().head(20)

fig, ax = plt.subplots(figsize=(12, 6))
top_zones.plot(kind='barh', ax=ax, color='steelblue')
ax.set_title('구역별 가로등 수 Top 20', fontsize=14, fontweight='bold')
ax.set_xlabel('가로등 수')
ax.invert_yaxis()
plt.tight_layout()
plt.show()

print(top_zones)

# 가로등 분포 산점도
fig, ax = plt.subplots(figsize=(10, 10))
ax.scatter(df['경도'], df['위도'], s=0.5, alpha=0.4, color='gold', linewidths=0)
ax.set_facecolor('#1a1a2e')
fig.patch.set_facecolor('#1a1a2e')
ax.set_title('서울시 가로등 위치 분포', color='white', fontsize=14, fontweight='bold')
ax.set_xlabel('경도', color='white')
ax.set_ylabel('위도', color='white')
ax.tick_params(colors='white')
plt.tight_layout()
plt.show()

# Folium 인터랙티브 지도 (샘플 500개)
sample = df.sample(n=min(500, len(df)), random_state=42)

m = folium.Map(
    location=[37.5665, 126.9780],
    zoom_start=11,
    tiles='CartoDB dark_matter'
)

for _, row in sample.iterrows():
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=3,
        color='#FFD700',
        fill=True,
        fill_color='#FFD700',
        fill_opacity=0.8,
        popup=row['관리번호']
    ).add_to(m)

print(f'지도에 표시된 가로등: {len(sample)}개 (전체 {len(df):,}개 중 샘플)')
m

"""## Step 5. 결과 저장"""

# 정상 데이터 저장
output_filename = '서울시_가로등_전처리완료.csv'
df.to_csv(output_filename, index=False, encoding='utf-8-sig')  # utf-8-sig: 엑셀 호환
print(f'✅ 저장 완료: {output_filename}')
print(f'   행 수: {len(df):,}건  |  컬럼: {list(df.columns)}')

# 이상치 별도 저장
if len(df_invalid) > 0:
    invalid_filename = '서울시_가로등_이상치.csv'
    df_invalid.to_csv(invalid_filename, index=False, encoding='utf-8-sig')
    print(f'⚠️  이상치 저장: {invalid_filename}  ({len(df_invalid)}건)')

# Colab에서 로컬로 다운로드
files.download(output_filename)
if len(df_invalid) > 0:
    files.download(invalid_filename)

"""---
## 📝 전처리 정리

| 단계 | 처리 내용 | 제거 건수 |
|------|-----------|----------|
| 중복 제거 | `drop_duplicates()` | 0건 |
| 결측치 제거 | 위도/경도/관리번호 null 제거 | 0건 |
| 좌표 이상치 제거 | 서울 범위(위도 37.4~37.7, 경도 126.7~127.2) 벗어난 행 | **25건** |
| 컬럼 추가 | `관리번호`에서 `구역명`, `순번` 분리 | — |

> ⚠️ **이상치 원인**: `용비교` 구간 25건의 위도=0, 경도=4664046 → 좌표계 오류(TM/UTM 좌표가 WGS84 자리에 입력된 것으로 추정). 원본 데이터 담당자 확인 권장.
"""